apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistentvolume
  namespace: gb4
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  storageClassName: local
